name: Node.js Package on npm

on:
  release:
    types: [created]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v6
      with:
        node-version: '24'
        registry-url: 'https://registry.npmjs.org'
        scope: '@cosmotech'
    - run: npm version ${{ github.event.release.tag_name }} --allow-same-version --no-git-tag-version
    - run: npm install
    - run: npm publish --tag ${{ github.event.release.prerelease && 'prerelease' || 'latest' }}
